CREATE TABLE EMP2
(
    EMPNO   NUMBER(4) PRIMARY KEY,
    ENAME   VARCHAR2(10) UNIQUE,
    SAL     NUMBER(7),
    DEPTNO  NUMBER(2),
    HIREBAR DATE,
    MGR     NUMBER(4),
    JOB     VARCHAR2(20),
    CONSTRAINT FK_DEPT2 FOREIGN KEY (DEPTNO) REFERENCES DEPT2 (DEPTNO)
);
/*
DROP TABLE SALGRADE;
DROP TABLE EMP1;
DROP TABLE DEPT;
*/
CREATE TABLE DEPT2
(
    DEPTNO NUMBER(2) UNIQUE,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
);

CREATE TABLE SALGRADE2
(
    GRADE NUMBER PRIMARY KEY,
    LOSAL NUMBER,
    HISAL NUMBER
);

SELECT *
FROM SALGRADE2;

ALTER TABLE EMP2
    ADD (COMM NUMBER(10));
ALTER TABLE EMP2
    MODIFY ENAME VARCHAR2(20) DEFAULT ('刘思远');
ALTER TABLE EMP2
    ADD (GRADE NUMBER
        CONSTRAINT FK_GRADE2 REFERENCES SALGRADE2 (GRADE)
        );
ALTER TABLE EMP2
    DROP (COMM);

CREATE UNIQUE INDEX emp_sname0173 ON EMP2 (ENAME);
CREATE UNIQUE INDEX e_de0173 ON EMP2 (DEPTNO ASC, ENAME DESC);

DROP INDEX emp_sname0173;
DROP INDEX e_de0173;

INSERT INTO SALGRADE2(GRADE, LOSAL, HISAL)
VALUES (1, 700, 4000);
INSERT INTO SALGRADE2(GRADE, LOSAL, HISAL)
VALUES (2, 2000, 9000);
INSERT INTO SALGRADE2(GRADE, LOSAL, HISAL)
VALUES (3, 3000, 15000);
INSERT INTO SALGRADE2(GRADE, LOSAL, HISAL)
VALUES (4, 8000, 20000);
INSERT INTO SALGRADE2(GRADE, LOSAL, HISAL)
VALUES (5, 10000, 50000);

INSERT INTO DEPT2(DEPTNO, DNAME, LOC)
VALUES (10, '华山派', '山西省渭南市');
INSERT INTO DEPT2(DEPTNO, DNAME, LOC)
VALUES (20, '日月神教', '黑木崖');
INSERT INTO DEPT2(DEPTNO, DNAME, LOC)
VALUES (30, '衡山派', '湖南省衡山县');
INSERT INTO DEPT2(DEPTNO, DNAME, LOC)
VALUES (40, '少林寺', '河南省登封市');

INSERT INTO EMP2(EMPNO, ENAME, SAL, DEPTNO, HIREBAR, MGR, JOB, GRADE)
VALUES (1000, '令狐冲', 4000, 10, TO_DATE('2015-3-2', 'YYYY-MM-DD'), 1000, '经理', 3);
INSERT INTO EMP2(EMPNO, ENAME, SAL, DEPTNO, HIREBAR, MGR, JOB, GRADE)
VALUES (1001, '刘晨', 3000, 20, TO_DATE('2010-08-26', 'YYYY-MM-DD'), NULL, '总经理', 4);
INSERT INTO EMP2(EMPNO, ENAME, SAL, DEPTNO, HIREBAR, MGR, JOB, GRADE)
VALUES (1003, '岳不群', 10000, 10, TO_DATE('2008-09-20', 'YYYY-MM-DD'), NULL, '董事长', 5);
INSERT INTO EMP2(EMPNO, ENAME, SAL, DEPTNO, HIREBAR, MGR, JOB, GRADE)
VALUES (1004, '岳灵珊', 4000, 10, TO_DATE('2009-10-25', 'YYYY-MM-DD'), 1003, '办事员', 1);

SELECT *
FROM EMP2;

UPDATE EMP2
SET SAL = SAL * 2
WHERE DEPTNO = 10;

UPDATE EMP2
SET ENAME = '岳灵珊'
WHERE EMPNO = 1004;

SELECT *
FROM EMP2;

DELETE
FROM EMP2
WHERE DEPTNO = (
    SELECT DEPTNO
    FROM DEPT2
    WHERE DNAME = '日月神教'
);

DELETE
FROM EMP2
WHERE EMPNO > 7900;
