CREATE TABLE EMP
(
    EMPNO   NUMBER(4) PRIMARY KEY,
    ENAME   VARCHAR2(10) UNIQUE,
    SAL     NUMBER(7),
    DEPTNO  NUMBER(2),
    HIREBAR DATE,
    MGR     NUMBER(4),
    JOB     VARCHAR2(20),
    CONSTRAINT FK_DEPT FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO)
);
/*
DROP TABLE SALGRADE;
DROP TABLE EMP;
DROP TABLE DEPT;
*/
CREATE TABLE DEPT
(
    DEPTNO NUMBER(2) UNIQUE,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
);

CREATE TABLE SALGRADE
(
    GRADE NUMBER PRIMARY KEY,
    LOSAL NUMBER,
    HISAL NUMBER
);

SELECT *
FROM SALGRADE;

ALTER TABLE EMP
    ADD (COMM NUMBER(10));
ALTER TABLE EMP
    MODIFY ENAME VARCHAR2(20) DEFAULT ('刘思远');
ALTER TABLE EMP
    ADD (GRADE NUMBER
        CONSTRAINT FK_GRADE REFERENCES SALGRADE (GRADE)
        );
ALTER TABLE EMP
    DROP (COMM);

CREATE UNIQUE INDEX emp_sname0173 ON EMP (ENAME);
CREATE UNIQUE INDEX e_de0173 ON EMP (DEPTNO ASC, ENAME DESC);

DROP INDEX emp_sname0173;
DROP INDEX e_de0173;

INSERT INTO SALGRADE(GRADE, LOSAL, HISAL)
VALUES (1, 700, 4000);
INSERT INTO SALGRADE(GRADE, LOSAL, HISAL)
VALUES (2, 2000, 9000);
INSERT INTO SALGRADE(GRADE, LOSAL, HISAL)
VALUES (3, 3000, 15000);
INSERT INTO SALGRADE(GRADE, LOSAL, HISAL)
VALUES (4, 8000, 20000);
INSERT INTO SALGRADE(GRADE, LOSAL, HISAL)
VALUES (5, 10000, 50000);

INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES (10, '华山派', '山西省渭南市');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES (20, '日月神教', '黑木崖');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES (30, '衡山派', '湖南省衡山县');
INSERT INTO DEPT(DEPTNO, DNAME, LOC)
VALUES (40, '少林寺', '河南省登封市');

INSERT INTO EMP(EMPNO, ENAME, SAL, DEPTNO, HIREBAR, MGR, JOB, GRADE)
VALUES (1000, '令狐冲', 4000, 10, TO_DATE('2015-3-2', 'YYYY-MM-DD'), 1000, '经理', 3);
INSERT INTO EMP(EMPNO, ENAME, SAL, DEPTNO, HIREBAR, MGR, JOB, GRADE)
VALUES (1001, '刘晨', 3000, 20, TO_DATE('2010-08-26', 'YYYY-MM-DD'), NULL, '总经理', 4);
INSERT INTO EMP(EMPNO, ENAME, SAL, DEPTNO, HIREBAR, MGR, JOB, GRADE)
VALUES (1003, '岳不群', 10000, 10, TO_DATE('2008-09-20', 'YYYY-MM-DD'), NULL, '董事长', 5);
INSERT INTO EMP(EMPNO, ENAME, SAL, DEPTNO, HIREBAR, MGR, JOB, GRADE)
VALUES (1004, '岳灵珊', 4000, 10, TO_DATE('2009-10-25', 'YYYY-MM-DD'), 1003, '办事员', 1);

UPDATE EMP
SET SAL = SAL * 2
WHERE DEPTNO = 10;

SELECT * FROM SALGRADE;
rollback;