SELECT *
FROM STUDENT;
SELECT *
FROM COURSE;
SELECT *
FROM SC;

SELECT SNO, SNAME
FROM STUDENT
WHERE SDEPT = 'MA';

SELECT DISTINCT SNO
FROM SC;

SELECT SNO, GRADE
FROM SC
WHERE CNO = '2'
ORDER BY GRADE DESC, SNO ASC;

SELECT SNO, 0.8 * GRADE
FROM SC
WHERE CNO = '2'
  AND GRADE BETWEEN 80 AND 90;

SELECT *
FROM STUDENT
WHERE SDEPT IN ('MA', 'CS')
  AND SNAME LIKE '张%';

SELECT SNO, CNO
FROM SC
WHERE GRADE IS NULL;

SELECT CNO, COUNT(*)
FROM SC
GROUP BY CNO;

SELECT *
FROM STUDENT,
     SC
WHERE STUDENT.SNO = SC.SNO;

SELECT STUDENT.SNO, SNAME, CNO, GRADE
FROM STUDENT,
     SC
WHERE STUDENT.SNO = SC.SNO;

SELECT STUDENT.SNO, SNAME, GRADE
FROM STUDENT,
     SC
WHERE STUDENT.SNO = SC.SNO
  AND CNO = '1'
  AND GRADE > 90;

SELECT FIRST.CNO, SECOND.CPNO
FROM COURSE FIRST,
     COURSE SECOND
WHERE FIRST.CPNO = SECOND.CNO;

SELECT *
FROM STUDENT
WHERE SDEPT IN (SELECT SDEPT FROM STUDENT WHERE SNAME = '刘晨');

SELECT S2.*
FROM STUDENT S1,
     STUDENT S2
WHERE S1.SNAME = '刘晨'
  AND S1.SDEPT = S2.SDEPT;

SELECT STUDENT.SNO, SNAME
FROM STUDENT,
     SC,
     COURSE
WHERE STUDENT.SNO = SC.SNO
  AND SC.CNO = COURSE.CNO
  AND CNAME = '信息系统';

SELECT SNO, AVG(GRADE)
FROM SC
GROUP BY SNO
HAVING AVG(GRADE) > 80;

SELECT SNO, COUNT(*)
FROM SC
GROUP BY SNO
HAVING COUNT(CNO) > 1;


SELECT SNO, SNAME
FROM STUDENT
WHERE SNO IN
      (SELECT SNO
       FROM SC
       WHERE CNO IN (
           SELECT CNO
           FROM COURSE
           WHERE CNAME = '信息系统'
       ));

SELECT *
FROM STUDENT;
SELECT *
FROM COURSE;
SELECT *
FROM SC;

SELECT STUDENT.SNO, SNAME
FROM STUDENT,
     SC,
     COURSE
WHERE CNAME = '信息系统'
  AND STUDENT.SNO = SC.SNO
  AND SC.CNO = COURSE.CNO;

SELECT S1.*
FROM STUDENT S1,
     STUDENT S2
WHERE S1.SDEPT = S2.SDEPT
  AND S2.SNAME = '刘晨 ';

SELECT *
FROM STUDENT
WHERE SDEPT IN (
    SELECT SDEPT
    FROM STUDENT
    WHERE SNAME = '刘晨'
);

INSERT INTO SC(SNO, CNO, GRADE)
VALUES ('200215121', '1', 92);

SELECT SNO, GRADE
FROM SC
WHERE CNO = '1'
  AND GRADE > (
    SELECT MAX(GRADE)
    FROM SC
    WHERE SNO IN (
        SELECT SNO
        FROM STUDENT
        WHERE SNAME = '刘晨'
    )
);

SELECT *
FROM SC;

SELECT *
FROM STUDENT
WHERE SAGE < (
    SELECT MAX(SAGE)
    FROM STUDENT
    WHERE SDEPT = 'CS'
)
  AND SDEPT != 'CS';

SELECT *
FROM STUDENT
WHERE SAGE < (
    SELECT MIN(SAGE)
    FROM STUDENT
    WHERE SDEPT = 'CS'
)
  AND SDEPT != 'CS';

SELECT SNAME
FROM STUDENT
WHERE NOT EXISTS(
        SELECT *
        FROM SC
        WHERE SNO = STUDENT.SNO
          AND CNO = 3
    );

SELECT SNAME
FROM STUDENT
MINUS
SELECT DISTINCT SNAME
FROM STUDENT
WHERE SNO IN (
    SELECT SNO
    FROM SC
    WHERE CNO = 3
);

SELECT SNAME
FROM STUDENT
WHERE NOT EXISTS(
        SELECT CNO
        FROM COURSE
        MINUS
        SELECT CNO
        FROM SC
        WHERE SC.SNO = STUDENT.SNO
    );

SELECT SNAME
FROM STUDENT
WHERE NOT EXISTS(
        SELECT *
        FROM COURSE
        WHERE NOT EXISTS(
                SELECT *
                FROM SC
                WHERE SNO = STUDENT.SNO
                  AND CNO = COURSE.CNO
            )
    );


SELECT *
FROM STUDENT;
SELECT *
FROM SC;

SELECT SNAME, STUDENT.SNO
FROM STUDENT,
     SC
WHERE STUDENT.SNO = SC.SNO
GROUP BY SNAME, STUDENT.SNO
HAVING COUNT(*) >= (
    SELECT COUNT(*)
    FROM SC
    WHERE SNO = '200215121'
);

SELECT SNAME, SNO
FROM STUDENT
WHERE SNO IN (
    SELECT SNO
    FROM SC SCX
    WHERE NOT EXISTS(
            SELECT *
            FROM SC SCY
            WHERE SCY.SNO = '200215121'
              AND NOT EXISTS(
                    SELECT *
                    FROM SC SCZ
                    WHERE SCZ.SNO = SCX.SNO
                      AND SCZ.CNO = SCY.CNO
                )
        )
);

SELECT SNO, SNAME
FROM STUDENT
WHERE SNO IN (
    SELECT SNO
    FROM SC
    GROUP BY SNO
    HAVING COUNT(*) >= (2)
);

SELECT SNAME, STUDENT.SNO
FROM STUDENT,
     SC
WHERE SC.SNO = STUDENT.SNO
GROUP BY SNAME, STUDENT.SNO
HAVING COUNT(*) >= (2);

SELECT *
FROM SC;

CREATE VIEW CS_STUDENT
AS
SELECT SNO, SNAME, SAGE
FROM STUDENT
WHERE SDEPT = 'CS';

SELECT * FROM CS_STUDENT;

CREATE VIEW CS_S1
AS
SELECT CS_STUDENT.SNO, SNAME, SAGE, GRADE
FROM CS_STUDENT, SC
WHERE CS_STUDENT.SNO = SC.SNO
AND CNO = '1';

SELECT * FROM CS_S1;

CREATE VIEW SNO_AVG(SNO, AVG)
AS
SELECT STUDENT.SNO, AVG(GRADE)
FROM STUDENT, SC
WHERE STUDENT.SNO = SC.SNO
GROUP BY STUDENT.SNO;

SELECT * FROM SNO_AVG;

CREATE VIEW S_FEMALE(SNO, SNAME, SDEPT, SSEX)
AS
SELECT SNO, SNAME, SDEPT, SSEX
FROM STUDENT
WHERE SSEX = '女'
WITH CHECK OPTION ;

SELECT * FROM S_FEMALE;

INSERT INTO
S_FEMALE(SNO, SNAME, SDEPT)
VALUES('200215129', 'SMITH', 'MA');

INSERT INTO
S_FEMALE(SNO, SNAME, SDEPT, SSEX)
VALUES('200215129', 'SMITH', 'MA', '女');
