CREATE TABLE EMP
(
    EMPNO   NUMBER(4) PRIMARY KEY,
    ENAME   VARCHAR2(10),
    SAL     NUMBER(7),
    DEPTNO  NUMBER(2) UNIQUE,
    HIREBAR DATE,
    MGR     NUMBER(4),
    JOB     VARCHAR2(20)
);
/*
DROP TABLE SALGRADE;
DROP TABLE EMP;
DROP TABLE DEPT;
*/

CREATE TABLE DEPT
(
    DEPTNO NUMBER(2) UNIQUE,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13),
    CONSTRAINT FK_DEPT FOREIGN KEY (DEPTNO) REFERENCES EMP (DEPTNO)
);

CREATE TABLE SALGRADE
(
    GRADE NUMBER PRIMARY KEY,
    LOSAL NUMBER,
    HISAL NUMBER
);

SELECT *
FROM SALGRADE;

ALTER TABLE EMP
    ADD (COMM NUMBER(10));
ALTER TABLE EMP
    MODIFY ENAME VARCHAR2(20) DEFAULT ('刘思远');
ALTER TABLE EMP
    ADD (GRADE NUMBER
        CONSTRAINT FK_GRADE REFERENCES SALGRADE (GRADE)
        );
ALTER TABLE EMP
    DROP (COMM);

