SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM SC;

SELECT SNO, SNAME FROM STUDENT WHERE SDEPT = 'MA'

SELECT DISTINCT SNO FROM SC 
SELECT SNO, GRADE FROM SC WHERE CNO = '2' ORDER BY GRADE DESC, SNO ASC;
SELECT SNO, 0.8 * GRADE FROM SC WHERE CNO = '2' AND GRADE BETWEEN 80 AND 90;
SELECT * FROM STUDENT WHERE SDEPT IN ('MA', 'CS') AND SNAME LIKE '张%';
SELECT SNO, CNO FROM SC WHERE GRADE IS NULL;
SELECT CNO, COUNT(*) FROM SC GROUP BY CNO; 

SELECT * FROM STUDENT, SC WHERE STUDENT.SNO = SC.SNO;
SELECT STUDENT.SNO, SNAME, CNO, GRADE FROM STUDENT, SC WHERE STUDENT.SNO = SC.SNO; 
SELECT STUDENT.SNO, SNAME, GRADE FROM STUDENT, SC WHERE STUDENT.SNO = SC.SNO AND CNO = '1' AND GRADE > 90;

SELECT FIRST.CNO, SECOND.CPNO FROM COURSE FIRST, COURSE SECOND WHERE FIRST.CPNO = SECOND.CNO;
SELECT * FROM STUDENT WHERE SDEPT IN (SELECT SDEPT FROM STUDENT WHERE SNAME = '刘晨');
SELECT S2.* FROM STUDENT S1, STUDENT S2 WHERE S1.SNAME = '刘晨' AND S1.SDEPT = S2.SDEPT;
SELECT STUDENT.SNO, SNAME FROM STUDENT, SC, COURSE WHERE STUDENT.SNO = SC.SNO AND SC.CNO = COURSE.CNO AND CNAME = '信息系统'; 
SELECT SNO, AVG(GRADE) FROM SC GROUP BY SNO HAVING AVG(GRADE) > 80;
SELECT SNO, COUNT(*) FROM SC GROUP BY SNO HAVING COUNT(CNO) > 1;

SELECT SNO, SNAME FROM STUDENT WHERE 





